# Generated by Django 4.1.4 on 2023-01-30 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_usersprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path_for_post),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path_for_profile),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'None')], default='N', max_length=1)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path_for_profile)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, to='posts.profile')),
                ('following', models.ManyToManyField(blank=True, to='posts.profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
