# Generated by Django 4.1.4 on 2023-01-31 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_image_alter_usersprofile_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersProfile',
        ),
    ]
